### ISSUE TITLE
Python package installation issues

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/docker#26]
Seeing this message:

```
#8 53.84   Downloading Cartopy-0.18.0.tar.gz (14.4 MB)
#8 53.99      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.4/14.4 MB 92.6 MB/s eta 0:00:00
#8 54.39   Preparing metadata (setup.py): started
#8 54.63   Preparing metadata (setup.py): finished with status 'error'
#8 54.64   error: subprocess-exited-with-error
#8 54.64   
#8 54.64   × python setup.py egg_info did not run successfully.
#8 54.64   │ exit code: 1
#8 54.64   ╰─> [13 lines of output]
#8 54.64       Traceback (most recent call last):
#8 54.64         File "/tmp/pip-install-xpr0hdls/cartopy_f8366d3bf5f44cd6b51d81b49e18c0f5/setup.py", line 43, in <module>
#8 54.64           import numpy as np
#8 54.64       ModuleNotFoundError: No module named 'numpy'
#8 54.64       
#8 54.64       During handling of the above exception, another exception occurred:
#8 54.64       
#8 54.64       Traceback (most recent call last):
#8 54.64         File "<string>", line 2, in <module>
#8 54.64         File "<pip-setuptools-caller>", line 34, in <module>
#8 54.64         File "/tmp/pip-install-xpr0hdls/cartopy_f8366d3bf5f44cd6b51d81b49e18c0f5/setup.py", line 45, in <module>
#8 54.64           raise ImportError('NumPy 1.10+ is required to install cartopy.')
#8 54.64       ImportError: NumPy 1.10+ is required to install cartopy.
#8 54.64       [end of output]
```

Source: https://github.com/geocompr/docker/runs/7054120092?check_suite_focus=true#step:8:736 Any ideas welcome, call for help in the dark @martinfleis!

**Comment by martinfleis** [comment]
`Cartopy` doesn't have compiled wheels uploaded on PyPI, which means that every time you try installing it with `pip`, you need to compile it. Since it depends on GDAL, it is more often than not a source of a trouble. Don't know why they do not offer wheels, apart from a guess that is is non trivial to make them.

You can try debugging this, but I would heavily recommend going forward with #27 and installing everything with a strict channel priority from the `conda-forge` channel.

**Comment by Robinlovelace** [comment]
Many thanks for the wise advice Martin. I will follow it!

**Comment by Robinlovelace** [comment]
Heads-up @anitagraser, I saw this issue and thought it may be of interest: 

```
Discarding https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.5): Requested cartopy from https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from movingpandas) has inconsistent version: filename has '0.19.0.post1', but metadata has '0.0'
```


Source: https://github.com/geocompr/docker/runs/7060091673?check_suite_focus=true#step:8:719

I plan to remove movingpandas for now...

**Comment by anitagraser** [comment]
Sure. We don't need it for the basics anyway.
